site_name: acai-ts
site_url: https://syngenta.github.io/acai-ts-docs
site_author: Paul Cruse III
site_dir: ../docs
nav:
    - Home: index.md
    - Tutorials:
        - demo.md
    - install.md
    - Decorators:
        - decorators/index.md
    - Event Handlers:
        - APIGateway:
            - apigateway/index.md
            - Router:
                - apigateway/router/setup.md
                - apigateway/router/configurations.md
            - Endpoint:
                - apigateway/endpoint/setup.md
                - apigateway/endpoint/configurations.md
            - apigateway/request.md
            - apigateway/response.md
        - DynamoDB:
            - dynamodb/index.md
            - dynamodb/configurations.md
            - dynamodb/record.md
        - S3:
            - s3/index.md
            - s3/configurations.md
            - s3/record.md
        - SQS:
            - sqs/index.md
            - sqs/configurations.md
            - sqs/record.md
    - common/logger.md
    - troubleshooting.md
    - changes.md
    - NPM Registry: https://www.npmjs.com/package/acai-ts
    - Github Repository: https://github.com/syngenta/acai-ts
    - Issues: https://github.com/syngenta/acai-ts/issues
theme:
    name: material
    logo: https://raw.githubusercontent.com/syngenta/acai-ts-docs/main/logos/logo-icon-docs.png
    palette:
        -
            scheme: acai
    highlightjs: true
    hljs_languages:
        - typescript
        - yaml
        - json
    shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s
    features:
        - navigation.top
        - navigation.instant
        - navigation.indexes
        - navigation.tracking
        - content.code.annotate
markdown_extensions:
    - codehilite
    - meta
    - admonition
    - pymdownx.details
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight:
        linenums: true
    - pymdownx.snippets:
        base_path: "."
        check_paths: true
    - toc:
        permalink: true
        toc_depth: 4
    - pymdownx.superfences:
        custom_fences:
            -
                name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
    - search
extra:
    web:
        url: https://syngenta.github.io/acai-ts-docs
extra_css:
    - extra.css
